apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "covenant-connect.backendName" . }}
  labels:
    {{- include "covenant-connect.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "covenant-connect.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "covenant-connect.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: {{ printf "%s:%s" .Values.backend.image.repository .Values.backend.image.tag | quote }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              name: http
          env:
            - name: APP_VERSION
              value: {{ default .Chart.AppVersion .Values.backend.env.APP_VERSION | quote }}
            {{- range $key, $value := .Values.backend.env }}
            {{- if ne $key "APP_VERSION" }}
            - name: {{ $key }}
              value: {{ tpl (printf "%v" $value) $ | quote }}
            {{- end }}
            {{- end }}
            {{- range $key, $_ := .Values.backend.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "covenant-connect.backendSecretName" $ }}
                  key: {{ $key }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
