{{- if and .Values.redis.auth.enabled (not .Values.redis.auth.password) -}}
{{- fail "redis.auth.password must be set when redis.auth.enabled is true" -}}
{{- end -}}
{{- $backendSecret := include "covenant-connect.backendSecretName" . -}}
{{- $postgresHost := printf "%s:%d" (include "covenant-connect.postgresName" .) (.Values.postgres.service.port | default 5432) -}}
{{- $postgresUser := .Values.postgres.auth.username | default "postgres" -}}
{{- $postgresPassword := .Values.postgres.auth.password | default "postgres" -}}
{{- $postgresDatabase := .Values.postgres.auth.database | default "postgres" -}}
{{- $defaultDatabaseUrl := printf "postgresql://%s:%s@%s/%s?schema=public" $postgresUser $postgresPassword $postgresHost $postgresDatabase -}}
{{- $redisHost := printf "%s:%d" (include "covenant-connect.redisName" .) (.Values.redis.service.port | default 6379) -}}
{{- $defaultRedisUrl := ternary (printf "redis://:%s@%s/0" .Values.redis.auth.password $redisHost) (printf "redis://%s/0" $redisHost) (.Values.redis.auth.enabled | default false) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $backendSecret }}
  labels:
    {{- include "covenant-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ default "change-me" .Values.backend.secretEnv.SESSION_SECRET | quote }}
  DATABASE_URL: {{ default $defaultDatabaseUrl .Values.backend.secretEnv.DATABASE_URL | quote }}
  SHADOW_DATABASE_URL: {{ default "" .Values.backend.secretEnv.SHADOW_DATABASE_URL | quote }}
  REDIS_URL: {{ default $defaultRedisUrl .Values.backend.secretEnv.REDIS_URL | quote }}
  STRIPE_SECRET_KEY: {{ default "" .Values.backend.secretEnv.STRIPE_SECRET_KEY | quote }}
  STRIPE_WEBHOOK_SECRET: {{ default "" .Values.backend.secretEnv.STRIPE_WEBHOOK_SECRET | quote }}
  PAYSTACK_SECRET_KEY: {{ default "" .Values.backend.secretEnv.PAYSTACK_SECRET_KEY | quote }}
  PAYSTACK_WEBHOOK_SECRET: {{ default "" .Values.backend.secretEnv.PAYSTACK_WEBHOOK_SECRET | quote }}
  FINCRA_SECRET_KEY: {{ default "" .Values.backend.secretEnv.FINCRA_SECRET_KEY | quote }}
  FINCRA_WEBHOOK_SECRET: {{ default "" .Values.backend.secretEnv.FINCRA_WEBHOOK_SECRET | quote }}
  FLUTTERWAVE_SECRET_KEY: {{ default "" .Values.backend.secretEnv.FLUTTERWAVE_SECRET_KEY | quote }}
  FLUTTERWAVE_WEBHOOK_SECRET: {{ default "" .Values.backend.secretEnv.FLUTTERWAVE_WEBHOOK_SECRET | quote }}
  GOOGLE_CLIENT_ID: {{ default "" .Values.backend.secretEnv.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ default "" .Values.backend.secretEnv.GOOGLE_CLIENT_SECRET | quote }}
  FACEBOOK_CLIENT_ID: {{ default "" .Values.backend.secretEnv.FACEBOOK_CLIENT_ID | quote }}
  FACEBOOK_CLIENT_SECRET: {{ default "" .Values.backend.secretEnv.FACEBOOK_CLIENT_SECRET | quote }}
  APPLE_CLIENT_ID: {{ default "" .Values.backend.secretEnv.APPLE_CLIENT_ID | quote }}
  APPLE_TEAM_ID: {{ default "" .Values.backend.secretEnv.APPLE_TEAM_ID | quote }}
  APPLE_KEY_ID: {{ default "" .Values.backend.secretEnv.APPLE_KEY_ID | quote }}
  APPLE_PRIVATE_KEY: {{ default "" .Values.backend.secretEnv.APPLE_PRIVATE_KEY | quote }}
  AWS_S3_BUCKET: {{ default "" .Values.backend.secretEnv.AWS_S3_BUCKET | quote }}
  AWS_REGION: {{ default "us-east-1" .Values.backend.secretEnv.AWS_REGION | quote }}
  AWS_ACCESS_KEY_ID: {{ default "" .Values.backend.secretEnv.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "" .Values.backend.secretEnv.AWS_SECRET_ACCESS_KEY | quote }}
  ASSET_BASE_URL: {{ default "" .Values.backend.secretEnv.ASSET_BASE_URL | quote }}
  SESSION_TTL: {{ default "604800" .Values.backend.secretEnv.SESSION_TTL | quote }}
  COOKIE_SECURE: {{ default "true" .Values.backend.secretEnv.COOKIE_SECURE | quote }}
  COOKIE_DOMAIN: {{ default "" .Values.backend.secretEnv.COOKIE_DOMAIN | quote }}
  KPI_DIGEST_CRON: {{ default "0 7 * * 1" .Values.backend.secretEnv.KPI_DIGEST_CRON | quote }}
  FOLLOW_UP_CRON: {{ default "0 */6 * * *" .Values.backend.secretEnv.FOLLOW_UP_CRON | quote }}
