apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "covenant-connect.frontendName" . }}
  labels:
    {{- include "covenant-connect.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "covenant-connect.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "covenant-connect.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ printf "%s:%s" .Values.frontend.image.repository .Values.frontend.image.tag | quote }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
              name: http
          env:
            - name: APP_VERSION
              value: {{ default .Chart.AppVersion .Values.frontend.env.APP_VERSION | quote }}
            {{- range $key, $value := .Values.frontend.env }}
            {{- if ne $key "APP_VERSION" }}
            - name: {{ $key }}
              value: {{ tpl (printf "%v" $value) $ | quote }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
