apiVersion: v1
kind: Secret
metadata:
  name: {{ include "covenant-connect.postgresSecretName" . }}
  labels:
    {{- include "covenant-connect.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
