apiVersion: v1
kind: Service
metadata:
  name: {{ include "covenant-connect.postgresName" . }}
  labels:
    {{- include "covenant-connect.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "covenant-connect.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
