apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "covenant-connect.redisName" . }}
  labels:
    {{- include "covenant-connect.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "covenant-connect.redisName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "covenant-connect.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "covenant-connect.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              if [ -n "${REDIS_PASSWORD:-}" ]; then
                exec redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
              else
                exec redis-server --appendonly yes
              fi
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: redis
          {{- if and .Values.redis.auth.enabled .Values.redis.auth.password }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "covenant-connect.redisSecretName" . }}
                  key: REDIS_PASSWORD
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      {{- if not .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-data
          emptyDir: {}
      {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          {{- toYaml .Values.redis.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
        {{- if .Values.redis.persistence.storageClassName }}
        storageClassName: {{ .Values.redis.persistence.storageClassName }}
        {{- end }}
  {{- end }}
